name: fortune-cm
version: 3.20.0
base: core22
summary: Display a random fortune
description: |
  fortune is a command-line utility which displays a random quotation from a
  collection of quotes. This collection is read from the local file system and
  does not require network access.

  This is a build of fortune-mod from from https://github.com/shlomif/fortune-mod.
  It includes both inoffensive and offensive fortune databases, but the latter
  will only be accessed when the `-o` parameter is specified.

grade: stable
confinement: strict

parts:
  fortune:
    after: [docmake, rinutils]
    plugin: cmake
    source: https://github.com/shlomif/fortune-mod.git
    source-tag: fortune-mod-$SNAPCRAFT_PROJECT_VERSION
    source-subdir: fortune-mod
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DLOCALDIR=/usr/share/games/fortunes
    build-packages:
      - libpath-tiny-perl
      - librecode-dev
      - xsltproc
      - docbook-xsl
    stage-packages:
      - librecode0

  rinutils:
    plugin: cmake
    source: https://github.com/shlomif/rinutils.git
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
      - build-essential
      - pkg-config
      - libcmocka-dev
    prime:
      - -*

  docmake:
    plugin: nil
    build-packages:
      - cpanminus
    override-build: |
      cpanm App::XML::DocBook::Docmake
    prime:
      - -*

apps:
  fortune:
    command: usr/games/fortune

  strfile:
    command: usr/bin/strfile
    plugs:
      - home

  unstr:
    command: usr/bin/unstr
    plugs:
      - home

layout:
  /usr/share/games/fortunes:
    symlink: $SNAP/usr/share/games/fortunes
